---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJ6aGFvZ2FvbG9uZyIsInBhc3N3b3JkIjoiYWJlMTU3MjZjZDZhMzVlZTk3ZDI2NThjMmU1NmIxZTMyOTRkZmY5OCIsImVtYWlsIjoiemdhb2xvbmdAZ21haWwuY29tIiwiYXV0aCI6ImVtaGhiMmRoYjJ4dmJtYzZZV0psTVRVM01qWmpaRFpoTXpWbFpUazNaREkyTlRoak1tVTFObUl4WlRNeU9UUmtabVk1T0E9PSJ9fX0=
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: latency
  name: latency
spec:
  containers:
  - command:
    - sh
    - -c
    - /server
    image: docker.pkg.github.com/zhaogaolong/latency/server:latest
    imagePullPolicy: IfNotPresent
    name: latency
    ports:
    - containerPort: 8080
      protocol: TCP
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  imagePullSecrets:
  - name: regcred
  dnsPolicy: ClusterFirst
  priority: 0
